### ISSUE TITLE
Set up environment

### ISSUE THREAD

**Issue by antomus** [antomus/simple_http_server#1]
1. Install Vagrant https://www.vagrantup.com/                                                                             **Done

1. Download https://github.com/rails/rails-dev-box

1. Make sure you can ssh to VM and command `ruby -v` gives you information about Ruby version 

1. Install Sublime Text 3 https://www.sublimetext.com/3

-  Set next preferences 
{
	"color_scheme": "Packages/User/SublimeLinter/Twilight (SL).tmTheme",
	"ensure_newline_at_eof_on_save": false,
	"font_size": 14,
	"ignored_packages":
	[
		"Emmet",
		"Vintage"
	],
	"save_on_focus_lost": true,
	"tab_size": 2,
	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": true
}

- Install Package Control

- Install next packages
		"All Autocomplete",
		"GitGutter",
		"Package Control",
		"SideBarEnhancements",
		"SublimeGit",
		"SublimeLinter",
		"SublimeLinter-rubocop",
		"SublimeLinter-ruby"

**Comment by IvanSlezyn** [comment]
1.I got the result: vagrant 1.9.0;
2.I launched rails-dev-box on the Oracle VM VirtualBox;
3. I got the result: ruby 1.8.7 (2012-02-08 patchlevel 358) [x86_64-linux];
4. I installed all packages from your order;

**Comment by antomus** [comment]
ruby 1.8.7 (2012-02-08 patchlevel 358  - you've got a bit strange ruby version output. According to bootstrap.sh it should be  ruby-2.3.*. And it is 2.3.1 on my machine. Can you try to run `rvm -v` in VM's terminal ?

**Comment by IvanSlezyn** [comment]
i had tried to run rvm -v  but command not found

**Comment by antomus** [comment]
looks like wrong VM or bootstrap.sh failed during VM provisioning

**Comment by antomus** [comment]
Even simple task on Windows can get tricky, do yourself a favour next time start your development on Linux

**Comment by IvanSlezyn** [comment]
I promise you that!)
