### ISSUE TITLE
 Pass git quiz

### ISSUE THREAD

**Issue by antomus** [antomus/simple_http_server#4]
To prepare for the test be sure to read next docs

- https://git-scm.com/book/ru/v1

- http://eax.me/git-commands/

- https://marklodato.github.io/visual-git-guide/index-ru.html#basic-usage

test:
http://tutsplus.s3.amazonaws.com/tutspremium/courses_$folder$/Git-Essentials/quiz/index.html

## expected result:
The screenshot with test score is attached to the issue

**Comment by IvanSlezyn** [comment]
I read all three position rapidly, but  I can not remember all ((

**Comment by antomus** [comment]
you need to pass the test and attach screenshot of the test score to the issue. In order to attach the actual file just drag and drop it to comment form then press "comment"

**Comment by IvanSlezyn** [comment]
![default](https://cloud.githubusercontent.com/assets/24194687/20788466/93441924-b7b9-11e6-955f-7546a9b4481b.JPG)
